import type {
  AgentProfile,
  Approval,
  EvidenceItem,
  Execution,
  Experiment,
  HumanProfile,
  Integration,
  Override,
  Policy,
  ToolProfile,
  Venture,
  WeightSet,
  Workflow,
  WorkflowStep,
} from '@/lib/types';

export const weightSets: WeightSet[] = [
  {
    id: 'weights-2026-04-12',
    name: 'Freedom-first baseline',
    effectiveDate: '2026-04-12',
    notes:
      'Biases toward fast proof, owned workflows, and internal leverage while preserving governance discipline.',
    weights: {
      painIntensity: 1.1,
      revenueProximity: 1.2,
      workflowOwnership: 1.15,
      timeToProof: 1.15,
      dataMoatPotential: 0.9,
      distributionAdvantage: 1,
      governanceTractability: 1.1,
      technicalFeasibility: 1,
      internalStrategicLeverage: 1.15,
      founderUnfairAdvantage: 1.05,
    },
  },
  {
    id: 'weights-2026-03-29',
    name: 'Proof before platform',
    effectiveDate: '2026-03-29',
    notes:
      'Earlier draft that prioritized near-term revenue and feasibility while de-emphasizing platform buildout.',
    weights: {
      painIntensity: 1,
      revenueProximity: 1.25,
      workflowOwnership: 1.1,
      timeToProof: 1.2,
      dataMoatPotential: 0.8,
      distributionAdvantage: 1,
      governanceTractability: 1,
      technicalFeasibility: 1.1,
      internalStrategicLeverage: 0.95,
      founderUnfairAdvantage: 0.95,
    },
  },
];

export const ventures: Venture[] = [
  {
    id: 'venture-ai-consulting',
    slug: 'ai-consulting-build',
    name: 'AI Consulting Build',
    thesis:
      'Turn workflow diagnosis into implementation revenue by productizing readiness, roadmap, and governed delivery.',
    targetCustomer: 'Founder-led service businesses with 5-100 staff',
    targetMarket: 'North America SMB advisory and operations teams',
    coreWorkflowOwned: 'AI readiness audit to governed implementation plan',
    revenueModel: 'Fixed-fee diagnostic, implementation sprint, retained operating support',
    currentMaturity: 'Pilot revenue',
    costToDate: 9200,
    timeToProofWeeks: 4,
    distributionPath: 'Owner-led outbound, referrals, workshop follow-on offers',
    dataMoatNotes:
      'Cross-client workflow diagnostics, friction signatures, and implementation outcome library.',
    currentStatus: 'Priority candidate',
    scoreInputs: {
      painIntensity: 9,
      revenueProximity: 9,
      workflowOwnership: 8,
      timeToProof: 8,
      dataMoatPotential: 7,
      distributionAdvantage: 7,
      governanceTractability: 8,
      technicalFeasibility: 8,
      internalStrategicLeverage: 9,
      founderUnfairAdvantage: 8,
    },
    freedomMetrics: {
      founderHoursReclaimed: 12,
      scheduleFlexibility: 7,
      dependencyReduction: 5,
      decisionLatencyReduction: 8,
      incomeResilience: 8,
      familyCapacityProxy: 7,
      locationIndependenceProxy: 8,
      valueCreatedToEffortConsumed: 2.4,
    },
    integrations: ['integration-ai-consulting', 'integration-github'],
    evidenceIds: ['evidence-01', 'evidence-02', 'evidence-06'],
  },
  {
    id: 'venture-pdf-flow',
    slug: 'pdf-flow',
    name: 'EasyDraftDocs / PDF Flow',
    thesis:
      'Own high-friction PDF workflows end to end, from intake through document output and customer delivery.',
    targetCustomer: 'Small business owners and legal-style admin workflows',
    targetMarket: 'Document-heavy service operations',
    coreWorkflowOwned: 'PDF intake, transformation, QA, and delivery',
    revenueModel: 'Self-serve subscriptions with premium operator assist',
    currentMaturity: 'Operational domain',
    costToDate: 18400,
    timeToProofWeeks: 3,
    distributionPath: 'Search intent, word-of-mouth, partner embeds',
    dataMoatNotes:
      'Document transformation telemetry, error taxonomy, and document-type optimization loops.',
    currentStatus: 'Execution domain',
    scoreInputs: {
      painIntensity: 8,
      revenueProximity: 8,
      workflowOwnership: 9,
      timeToProof: 9,
      dataMoatPotential: 8,
      distributionAdvantage: 6,
      governanceTractability: 9,
      technicalFeasibility: 8,
      internalStrategicLeverage: 7,
      founderUnfairAdvantage: 7,
    },
    freedomMetrics: {
      founderHoursReclaimed: 16,
      scheduleFlexibility: 8,
      dependencyReduction: 6,
      decisionLatencyReduction: 7,
      incomeResilience: 7,
      familyCapacityProxy: 8,
      locationIndependenceProxy: 8,
      valueCreatedToEffortConsumed: 2.1,
    },
    integrations: ['integration-pdf-flow'],
    evidenceIds: ['evidence-03', 'evidence-04'],
  },
  {
    id: 'venture-freedom-engine',
    slug: 'freedom-engine-os',
    name: 'The Freedom OS Engine',
    thesis:
      'Create an internal venture control plane that objectively allocates human and agent effort toward freedom-generating work.',
    targetCustomer: 'Internal venture studio and founder-operator team',
    targetMarket: 'Internal operating system first, future multi-tenant expansion second',
    coreWorkflowOwned: 'Portfolio prioritization, governance, execution orchestration, and review',
    revenueModel: 'Internal leverage now, platform licensing later',
    currentMaturity: 'Foundational build',
    costToDate: 6100,
    timeToProofWeeks: 6,
    distributionPath: 'Internal adoption, then founder-led case-study driven expansion',
    dataMoatNotes:
      'Decision logs, cross-venture evidence graphs, execution outcomes, and governance patterns.',
    currentStatus: 'Strategic platform',
    scoreInputs: {
      painIntensity: 7,
      revenueProximity: 5,
      workflowOwnership: 9,
      timeToProof: 6,
      dataMoatPotential: 9,
      distributionAdvantage: 6,
      governanceTractability: 8,
      technicalFeasibility: 7,
      internalStrategicLeverage: 10,
      founderUnfairAdvantage: 9,
    },
    freedomMetrics: {
      founderHoursReclaimed: 10,
      scheduleFlexibility: 9,
      dependencyReduction: 8,
      decisionLatencyReduction: 10,
      incomeResilience: 6,
      familyCapacityProxy: 9,
      locationIndependenceProxy: 9,
      valueCreatedToEffortConsumed: 1.7,
    },
    integrations: ['integration-ai-consulting', 'integration-pdf-flow', 'integration-github'],
    evidenceIds: ['evidence-05', 'evidence-06'],
  },
];

export const experiments: Experiment[] = [
  {
    id: 'experiment-01',
    ventureId: 'venture-ai-consulting',
    name: 'Workflow teardown sprint',
    hypothesis:
      'A 5-day workflow decomposition product will convert faster than a generic AI strategy offer.',
    stage: 'running',
    owner: 'Adam Goodwin',
    nextCheckpoint: '2026-04-18',
  },
  {
    id: 'experiment-02',
    ventureId: 'venture-pdf-flow',
    name: 'Owner dashboard for PDF ops',
    hypothesis:
      'Surfacing queue risk, rework, and operator throughput will reduce avoidable intervention time.',
    stage: 'proposed',
    owner: 'Operator',
    nextCheckpoint: '2026-04-16',
  },
  {
    id: 'experiment-03',
    ventureId: 'venture-freedom-engine',
    name: 'Weekly review operating cadence',
    hypothesis:
      'A structured review loop will reduce founder bias and make venture allocation visibly evidence-backed.',
    stage: 'running',
    owner: 'Strategist',
    nextCheckpoint: '2026-04-19',
  },
];

export const workflows: Workflow[] = [
  {
    id: 'workflow-01',
    ventureId: 'venture-ai-consulting',
    name: 'Readiness diagnostic',
    purpose: 'Decompose a client workflow and convert it into a governed implementation plan.',
    latencyHours: 18,
    aiSuitability: 'high',
    governanceRisk: 'medium',
    requiredHumanApprovals: ['Offer scope', 'External commitments'],
    failurePoints: ['Weak intake context', 'Ambiguous owner approval', 'No evidence trail'],
  },
  {
    id: 'workflow-02',
    ventureId: 'venture-pdf-flow',
    name: 'PDF intake to delivery',
    purpose: 'Accept document jobs, transform files, QA output, and deliver value with low rework.',
    latencyHours: 6,
    aiSuitability: 'high',
    governanceRisk: 'medium',
    requiredHumanApprovals: ['Refunds', 'Exception handling'],
    failurePoints: ['Unreadable source files', 'Output quality misses', 'Queue spikes'],
  },
  {
    id: 'workflow-03',
    ventureId: 'venture-freedom-engine',
    name: 'Weekly capital and attention allocation',
    purpose:
      'Compare ventures and experiments, then decide where founder and agent energy should go next.',
    latencyHours: 3,
    aiSuitability: 'medium',
    governanceRisk: 'high',
    requiredHumanApprovals: ['Priority changes', 'Budget changes', 'Policy edits'],
    failurePoints: ['Founder bias', 'Stale weights', 'Weak evidence freshness'],
  },
];

export const workflowSteps: WorkflowStep[] = [
  {
    id: 'step-01',
    workflowId: 'workflow-01',
    name: 'Collect intake and constraints',
    actor: 'researcher',
    systemsTouched: ['Forms', 'CRM', 'GitHub'],
    handoffTo: 'workflow analyst',
    latencyMinutes: 45,
    aiSuitability: 'high',
    approvalRequired: false,
    governanceRisk: 'low',
  },
  {
    id: 'step-02',
    workflowId: 'workflow-01',
    name: 'Map workflows, handoffs, and bottlenecks',
    actor: 'workflow analyst',
    systemsTouched: ['Readiness workspace', 'Shared evidence room'],
    handoffTo: 'strategist',
    latencyMinutes: 120,
    aiSuitability: 'high',
    approvalRequired: false,
    governanceRisk: 'medium',
  },
  {
    id: 'step-03',
    workflowId: 'workflow-01',
    name: 'Draft scoped implementation path',
    actor: 'strategist',
    systemsTouched: ['Scoring engine', 'Recommendation engine'],
    handoffTo: 'human owner',
    latencyMinutes: 90,
    aiSuitability: 'medium',
    approvalRequired: true,
    governanceRisk: 'medium',
  },
  {
    id: 'step-04',
    workflowId: 'workflow-02',
    name: 'Ingest files and classify job',
    actor: 'operator',
    systemsTouched: ['Upload service', 'Queue'],
    handoffTo: 'coder',
    latencyMinutes: 15,
    aiSuitability: 'high',
    approvalRequired: false,
    governanceRisk: 'low',
  },
  {
    id: 'step-05',
    workflowId: 'workflow-02',
    name: 'Transform and validate output',
    actor: 'QA reviewer',
    systemsTouched: ['PDF pipeline', 'Execution log'],
    handoffTo: 'operator',
    latencyMinutes: 30,
    aiSuitability: 'high',
    approvalRequired: false,
    governanceRisk: 'medium',
  },
  {
    id: 'step-06',
    workflowId: 'workflow-03',
    name: 'Refresh scores and evidence',
    actor: 'researcher',
    systemsTouched: ['Scoring engine', 'Evidence room'],
    handoffTo: 'governance reviewer',
    latencyMinutes: 40,
    aiSuitability: 'high',
    approvalRequired: false,
    governanceRisk: 'medium',
  },
  {
    id: 'step-07',
    workflowId: 'workflow-03',
    name: 'Run policy checks on recommendations',
    actor: 'governance reviewer',
    systemsTouched: ['Policy engine', 'Approval service'],
    handoffTo: 'human owner',
    latencyMinutes: 25,
    aiSuitability: 'medium',
    approvalRequired: true,
    governanceRisk: 'high',
  },
];

export const agents: AgentProfile[] = [
  {
    id: 'agent-researcher',
    role: 'Researcher',
    model: 'gpt-5.4-mini',
    autonomy: 'A1',
    defaultMode: 'ai-run',
    allowedActions: ['Collect evidence', 'Summarize findings', 'Create internal issues'],
    blockedActions: ['External commitments', 'Policy edits'],
    status: 'active',
  },
  {
    id: 'agent-strategist',
    role: 'Strategist',
    model: 'gpt-5.4',
    autonomy: 'A1',
    defaultMode: 'hybrid',
    allowedActions: ['Draft recommendations', 'Compare ventures', 'Draft experiments'],
    blockedActions: ['Reprioritize ventures without approval', 'Spend money'],
    status: 'active',
  },
  {
    id: 'agent-coder',
    role: 'Coder',
    model: 'gpt-5.3-codex',
    autonomy: 'A1',
    defaultMode: 'hybrid',
    allowedActions: ['Draft code', 'Open branches', 'Write tests'],
    blockedActions: ['Merge protected branches', 'Create production secrets'],
    status: 'active',
  },
  {
    id: 'agent-qa',
    role: 'QA reviewer',
    model: 'gpt-5.4-mini',
    autonomy: 'A1',
    defaultMode: 'ai-run',
    allowedActions: ['Validate outputs', 'Flag regressions', 'Attach evidence'],
    blockedActions: ['Override defects silently'],
    status: 'active',
  },
  {
    id: 'agent-docs',
    role: 'Documentation agent',
    model: 'gpt-5.4-mini',
    autonomy: 'A1',
    defaultMode: 'ai-run',
    allowedActions: ['Update docs', 'Draft reviews'],
    blockedActions: ['Approve policy exceptions'],
    status: 'active',
  },
  {
    id: 'agent-workflow',
    role: 'Workflow analyst',
    model: 'gpt-5.4',
    autonomy: 'A1',
    defaultMode: 'hybrid',
    allowedActions: ['Decompose workflows', 'Estimate latency', 'Classify automation fit'],
    blockedActions: ['Finalize external promises'],
    status: 'active',
  },
  {
    id: 'agent-governance',
    role: 'Governance reviewer',
    model: 'gpt-5.4',
    autonomy: 'A0',
    defaultMode: 'human-led',
    allowedActions: ['Run policy checks', 'Log exceptions', 'Require approvals'],
    blockedActions: ['Self-authorize irreversible actions'],
    status: 'guarded',
  },
  {
    id: 'agent-operator',
    role: 'Operator',
    model: 'gpt-5.4-mini',
    autonomy: 'A1',
    defaultMode: 'hybrid',
    allowedActions: ['Manage queues', 'Escalate exceptions', 'Execute approved tasks'],
    blockedActions: ['Change priorities', 'Spend money'],
    status: 'active',
  },
];

export const humans: HumanProfile[] = [
  {
    id: 'human-adam',
    name: 'Adam Goodwin',
    role: 'Owner',
    authority: ['Budget approval', 'Priority changes', 'External commitments', 'Policy changes'],
  },
  {
    id: 'human-tech-lead',
    name: 'Hybrid Session',
    role: 'Technical lead',
    authority: ['Architecture sign-off', 'Protected branch approval', 'Operational overrides'],
  },
  {
    id: 'human-ops',
    name: 'Operations lead',
    role: 'Operator',
    authority: ['Queue exceptions', 'Manual QA acceptance'],
  },
];

export const tools: ToolProfile[] = [
  {
    id: 'tool-github',
    name: 'GitHub',
    purpose: 'Issue creation, branch workflows, review collection, CI visibility',
    approvalRequired: 'Protected branch merge and repository admin changes',
    prohibitedUse: 'Silent merges or repo settings changes without human approval',
  },
  {
    id: 'tool-supabase',
    name: 'Supabase',
    purpose: 'Data persistence, auth, and auditable control-plane storage',
    approvalRequired: 'Schema changes in production',
    prohibitedUse: 'Production data deletion without runbook and approval',
  },
  {
    id: 'tool-shell',
    name: 'Local shell',
    purpose: 'Code execution, tests, and internal automation',
    approvalRequired: 'Commands with spending or destructive side effects',
    prohibitedUse: 'Destructive resets or unauthorized secrets access',
  },
  {
    id: 'tool-web',
    name: 'Web research',
    purpose: 'Collect external evidence and benchmark supporting context',
    approvalRequired: 'Publishing or outbound commitments',
    prohibitedUse: 'Unsourced recommendations presented as fact',
  },
];

export const policies: Policy[] = [
  {
    id: 'policy-01',
    name: 'Protected branch integrity',
    scope: 'Source control',
    rule: 'Agents may draft code and open branches but may not merge protected branches.',
    humanApprovalRequired: true,
  },
  {
    id: 'policy-02',
    name: 'Capital preservation',
    scope: 'Money movement',
    rule: 'Any spending, subscription creation, or financial commitment requires human approval.',
    humanApprovalRequired: true,
  },
  {
    id: 'policy-03',
    name: 'Priority authority',
    scope: 'Portfolio allocation',
    rule: 'Agents may recommend reprioritization but cannot enact it without owner approval.',
    humanApprovalRequired: true,
  },
  {
    id: 'policy-04',
    name: 'Evidence before recommendation',
    scope: 'Decision quality',
    rule: 'Recommendations must reference metrics, logs, workflow analysis, or prior outcomes.',
    humanApprovalRequired: false,
  },
];

export const approvals: Approval[] = [
  {
    id: 'approval-01',
    subject: 'AI Consulting Build offer redesign',
    owner: 'Adam Goodwin',
    status: 'approved',
    threshold: 'Owner sign-off',
  },
  {
    id: 'approval-02',
    subject: 'Freedom OS Engine scoring weight update',
    owner: 'Adam Goodwin',
    status: 'pending',
    threshold: 'Owner + governance reviewer',
  },
  {
    id: 'approval-03',
    subject: 'PDF Flow refund policy adjustment',
    owner: 'Operations lead',
    status: 'pending',
    threshold: 'Owner sign-off',
  },
];

export const evidenceItems: EvidenceItem[] = [
  {
    id: 'evidence-01',
    title: 'Readiness audit conversion notes',
    type: 'customer-signal',
    source: 'AI Consulting Build workshop log',
    summary: 'Prospects respond best when workflow bottlenecks are quantified with a next-step sprint offer.',
    relatedEntity: 'venture-ai-consulting',
  },
  {
    id: 'evidence-02',
    title: 'Proposal cycle time delta',
    type: 'metric',
    source: 'Internal tracking',
    summary: 'Workflow teardown package reduces proposal drafting time by roughly 38 percent.',
    relatedEntity: 'venture-ai-consulting',
  },
  {
    id: 'evidence-03',
    title: 'PDF throughput snapshot',
    type: 'metric',
    source: 'Clean PDF Build ops dashboard',
    summary: 'Queue spikes are concentrated in jobs requiring manual classification before transformation.',
    relatedEntity: 'venture-pdf-flow',
  },
  {
    id: 'evidence-04',
    title: 'Quality rework log',
    type: 'workflow-log',
    source: 'QA exception archive',
    summary: 'Most rework comes from ambiguous source documents and missing QA checkpoints.',
    relatedEntity: 'venture-pdf-flow',
  },
  {
    id: 'evidence-05',
    title: 'Founder time audit',
    type: 'financial',
    source: 'Weekly review worksheet',
    summary: 'Too much time is still spent switching between ventures without a clear allocation rule.',
    relatedEntity: 'venture-freedom-engine',
  },
  {
    id: 'evidence-06',
    title: 'Governance preflight baseline',
    type: 'governance',
    source: 'Repository preflight log',
    summary: 'The operating system repo now passes local governance preflight with zero warnings.',
    relatedEntity: 'venture-freedom-engine',
  },
];

export const executions: Execution[] = [
  {
    id: 'execution-01',
    workflowId: 'workflow-01',
    agentId: 'agent-workflow',
    status: 'completed',
    outcome: 'Workflow decomposition produced a sprint-ready consulting offer outline.',
    evidenceIds: ['evidence-01', 'evidence-02'],
    humanEscalation: true,
  },
  {
    id: 'execution-02',
    workflowId: 'workflow-02',
    agentId: 'agent-operator',
    status: 'awaiting-approval',
    outcome: 'Dashboard draft surfaced queue exceptions needing owner policy guidance.',
    evidenceIds: ['evidence-03', 'evidence-04'],
    humanEscalation: true,
  },
  {
    id: 'execution-03',
    workflowId: 'workflow-03',
    agentId: 'agent-governance',
    status: 'blocked',
    outcome: 'Priority update was held because the scoring weight change is still pending approval.',
    evidenceIds: ['evidence-05', 'evidence-06'],
    humanEscalation: true,
  },
];

export const overrides: Override[] = [
  {
    id: 'override-01',
    subject: 'Temporary manual prioritization of AI Consulting Build',
    reason: 'Immediate revenue learning outweighs platform sequencing this week.',
    owner: 'Adam Goodwin',
    followUp: 'Re-run scoring after next workshop sprint and either ratify or unwind the override.',
  },
];

export const integrations: Integration[] = [
  {
    id: 'integration-ai-consulting',
    name: 'AI Consulting Build',
    domain: 'Workflow readiness and implementation',
    status: 'live',
    note: 'Primary V1 operating domain and top candidate for first deep integration.',
  },
  {
    id: 'integration-pdf-flow',
    name: 'EasyDraftDocs / PDF Flow',
    domain: 'Document operations throughput',
    status: 'live',
    note: 'Provides measurable execution telemetry and owner dashboard use cases.',
  },
  {
    id: 'integration-github',
    name: 'GitHub workflow',
    domain: 'Code execution and review control plane',
    status: 'live',
    note: 'Used for issue creation, branches, reviews, and protected-branch controls.',
  },
];
