import type {
  AgentProfile,
  AgentBuildRequest,
  ArtifactPlacementDecision,
  Approval,
  CapabilityDefinition,
  CanonicalSourceLink,
  ConnectEvent,
  ConnectSession,
  DocumentationDecision,
  EscalationDecision,
  EscalationRequest,
  EvidenceItem,
  Execution,
  ExecutionBudget,
  Experiment,
  HumanProfile,
  Integration,
  KnowledgeArtifact,
  KnowledgeRetentionPolicy,
  OutboundDecision,
  Override,
  Policy,
  RetrievalRecord,
  SelfEvolvingFunction,
  SkillDefinition,
  SkillAcquisitionDecision,
  ToolProfile,
  TrustedContactPolicy,
  Venture,
  WeightSet,
  Workflow,
  WorkflowStep,
} from '@/lib/types';
import { getExecutionBudgetDefaults } from '@/lib/model-router';

export const weightSets: WeightSet[] = [
  {
    id: 'weights-2026-04-12',
    name: 'Freedom-first baseline',
    effectiveDate: '2026-04-12',
    notes:
      'Biases toward fast proof, owned workflows, and internal leverage while preserving governance discipline.',
    weights: {
      painIntensity: 1.1,
      revenueProximity: 1.2,
      workflowOwnership: 1.15,
      timeToProof: 1.15,
      dataMoatPotential: 0.9,
      distributionAdvantage: 1,
      governanceTractability: 1.1,
      technicalFeasibility: 1,
      internalStrategicLeverage: 1.15,
      founderUnfairAdvantage: 1.05,
    },
  },
  {
    id: 'weights-2026-03-29',
    name: 'Proof before platform',
    effectiveDate: '2026-03-29',
    notes:
      'Earlier draft that prioritized near-term revenue and feasibility while de-emphasizing platform buildout.',
    weights: {
      painIntensity: 1,
      revenueProximity: 1.25,
      workflowOwnership: 1.1,
      timeToProof: 1.2,
      dataMoatPotential: 0.8,
      distributionAdvantage: 1,
      governanceTractability: 1,
      technicalFeasibility: 1.1,
      internalStrategicLeverage: 0.95,
      founderUnfairAdvantage: 0.95,
    },
  },
];

export const ventures: Venture[] = [
  {
    id: 'venture-ai-consulting',
    slug: 'ai-consulting-build',
    name: 'AI Consulting Build',
    thesis:
      'Turn workflow diagnosis into implementation revenue by productizing readiness, roadmap, and governed delivery.',
    targetCustomer: 'Founder-led service businesses with 5-100 staff',
    targetMarket: 'North America SMB advisory and operations teams',
    coreWorkflowOwned: 'AI readiness audit to governed implementation plan',
    revenueModel: 'Fixed-fee diagnostic, implementation sprint, retained operating support',
    currentMaturity: 'Pilot revenue',
    costToDate: 9200,
    timeToProofWeeks: 4,
    distributionPath: 'Owner-led outbound, referrals, workshop follow-on offers',
    dataMoatNotes:
      'Cross-client workflow diagnostics, friction signatures, and implementation outcome library.',
    currentStatus: 'Priority candidate',
    scoreInputs: {
      painIntensity: 9,
      revenueProximity: 9,
      workflowOwnership: 8,
      timeToProof: 8,
      dataMoatPotential: 7,
      distributionAdvantage: 7,
      governanceTractability: 8,
      technicalFeasibility: 8,
      internalStrategicLeverage: 9,
      founderUnfairAdvantage: 8,
    },
    freedomMetrics: {
      founderHoursReclaimed: 12,
      scheduleFlexibility: 7,
      dependencyReduction: 5,
      decisionLatencyReduction: 8,
      incomeResilience: 8,
      familyCapacityProxy: 7,
      locationIndependenceProxy: 8,
      valueCreatedToEffortConsumed: 2.4,
    },
    integrations: ['integration-ai-consulting', 'integration-github'],
    evidenceIds: ['evidence-01', 'evidence-02', 'evidence-06'],
  },
  {
    id: 'venture-pdf-flow',
    slug: 'pdf-flow',
    name: 'EasyDraftDocs / PDF Flow',
    thesis:
      'Own high-friction PDF workflows end to end, from intake through document output and customer delivery.',
    targetCustomer: 'Small business owners and legal-style admin workflows',
    targetMarket: 'Document-heavy service operations',
    coreWorkflowOwned: 'PDF intake, transformation, QA, and delivery',
    revenueModel: 'Self-serve subscriptions with premium operator assist',
    currentMaturity: 'Operational domain',
    costToDate: 18400,
    timeToProofWeeks: 3,
    distributionPath: 'Search intent, word-of-mouth, partner embeds',
    dataMoatNotes:
      'Document transformation telemetry, error taxonomy, and document-type optimization loops.',
    currentStatus: 'Execution domain',
    scoreInputs: {
      painIntensity: 8,
      revenueProximity: 8,
      workflowOwnership: 9,
      timeToProof: 9,
      dataMoatPotential: 8,
      distributionAdvantage: 6,
      governanceTractability: 9,
      technicalFeasibility: 8,
      internalStrategicLeverage: 7,
      founderUnfairAdvantage: 7,
    },
    freedomMetrics: {
      founderHoursReclaimed: 16,
      scheduleFlexibility: 8,
      dependencyReduction: 6,
      decisionLatencyReduction: 7,
      incomeResilience: 7,
      familyCapacityProxy: 8,
      locationIndependenceProxy: 8,
      valueCreatedToEffortConsumed: 2.1,
    },
    integrations: ['integration-pdf-flow'],
    evidenceIds: ['evidence-03', 'evidence-04'],
  },
  {
    id: 'venture-freedom-engine',
    slug: 'freedom-engine-os',
    name: 'The Freedom OS Engine',
    thesis:
      'Create an internal venture control plane that objectively allocates human and agent effort toward freedom-generating work.',
    targetCustomer: 'Internal venture studio and founder-operator team',
    targetMarket: 'Internal operating system first, future multi-tenant expansion second',
    coreWorkflowOwned: 'Portfolio prioritization, governance, execution orchestration, and review',
    revenueModel: 'Internal leverage now, platform licensing later',
    currentMaturity: 'Foundational build',
    costToDate: 6100,
    timeToProofWeeks: 6,
    distributionPath: 'Internal adoption, then founder-led case-study driven expansion',
    dataMoatNotes:
      'Decision logs, cross-venture evidence graphs, execution outcomes, and governance patterns.',
    currentStatus: 'Strategic platform',
    scoreInputs: {
      painIntensity: 7,
      revenueProximity: 5,
      workflowOwnership: 9,
      timeToProof: 6,
      dataMoatPotential: 9,
      distributionAdvantage: 6,
      governanceTractability: 8,
      technicalFeasibility: 7,
      internalStrategicLeverage: 10,
      founderUnfairAdvantage: 9,
    },
    freedomMetrics: {
      founderHoursReclaimed: 10,
      scheduleFlexibility: 9,
      dependencyReduction: 8,
      decisionLatencyReduction: 10,
      incomeResilience: 6,
      familyCapacityProxy: 9,
      locationIndependenceProxy: 9,
      valueCreatedToEffortConsumed: 1.7,
    },
    integrations: ['integration-ai-consulting', 'integration-pdf-flow', 'integration-github'],
    evidenceIds: ['evidence-05', 'evidence-06'],
  },
];

export const experiments: Experiment[] = [
  {
    id: 'experiment-01',
    ventureId: 'venture-ai-consulting',
    name: 'Workflow teardown sprint',
    hypothesis:
      'A 5-day workflow decomposition product will convert faster than a generic AI strategy offer.',
    stage: 'running',
    owner: 'Adam Goodwin',
    nextCheckpoint: '2026-04-18',
  },
  {
    id: 'experiment-02',
    ventureId: 'venture-pdf-flow',
    name: 'Owner dashboard for PDF ops',
    hypothesis:
      'Surfacing queue risk, rework, and operator throughput will reduce avoidable intervention time.',
    stage: 'proposed',
    owner: 'Operator',
    nextCheckpoint: '2026-04-16',
  },
  {
    id: 'experiment-03',
    ventureId: 'venture-freedom-engine',
    name: 'Weekly review operating cadence',
    hypothesis:
      'A structured review loop will reduce founder bias and make venture allocation visibly evidence-backed.',
    stage: 'running',
    owner: 'Strategist',
    nextCheckpoint: '2026-04-19',
  },
];

export const workflows: Workflow[] = [
  {
    id: 'workflow-01',
    ventureId: 'venture-ai-consulting',
    name: 'Readiness diagnostic',
    purpose: 'Decompose a client workflow and convert it into a governed implementation plan.',
    latencyHours: 18,
    aiSuitability: 'high',
    governanceRisk: 'medium',
    requiredHumanApprovals: ['Offer scope', 'External commitments'],
    failurePoints: ['Weak intake context', 'Ambiguous owner approval', 'No evidence trail'],
  },
  {
    id: 'workflow-02',
    ventureId: 'venture-pdf-flow',
    name: 'PDF intake to delivery',
    purpose: 'Accept document jobs, transform files, QA output, and deliver value with low rework.',
    latencyHours: 6,
    aiSuitability: 'high',
    governanceRisk: 'medium',
    requiredHumanApprovals: ['Refunds', 'Exception handling'],
    failurePoints: ['Unreadable source files', 'Output quality misses', 'Queue spikes'],
  },
  {
    id: 'workflow-03',
    ventureId: 'venture-freedom-engine',
    name: 'Weekly capital and attention allocation',
    purpose:
      'Compare ventures and experiments, then decide where founder and agent energy should go next.',
    latencyHours: 3,
    aiSuitability: 'medium',
    governanceRisk: 'high',
    requiredHumanApprovals: ['Priority changes', 'Budget changes', 'Policy edits'],
    failurePoints: ['Founder bias', 'Stale weights', 'Weak evidence freshness'],
  },
];

export const workflowSteps: WorkflowStep[] = [
  {
    id: 'step-01',
    workflowId: 'workflow-01',
    name: 'Collect intake and constraints',
    actor: 'researcher',
    systemsTouched: ['Forms', 'CRM', 'GitHub'],
    handoffTo: 'workflow analyst',
    latencyMinutes: 45,
    aiSuitability: 'high',
    approvalRequired: false,
    governanceRisk: 'low',
  },
  {
    id: 'step-02',
    workflowId: 'workflow-01',
    name: 'Map workflows, handoffs, and bottlenecks',
    actor: 'workflow analyst',
    systemsTouched: ['Readiness workspace', 'Shared evidence room'],
    handoffTo: 'strategist',
    latencyMinutes: 120,
    aiSuitability: 'high',
    approvalRequired: false,
    governanceRisk: 'medium',
  },
  {
    id: 'step-03',
    workflowId: 'workflow-01',
    name: 'Draft scoped implementation path',
    actor: 'strategist',
    systemsTouched: ['Scoring engine', 'Recommendation engine'],
    handoffTo: 'human owner',
    latencyMinutes: 90,
    aiSuitability: 'medium',
    approvalRequired: true,
    governanceRisk: 'medium',
  },
  {
    id: 'step-04',
    workflowId: 'workflow-02',
    name: 'Ingest files and classify job',
    actor: 'operator',
    systemsTouched: ['Upload service', 'Queue'],
    handoffTo: 'coder',
    latencyMinutes: 15,
    aiSuitability: 'high',
    approvalRequired: false,
    governanceRisk: 'low',
  },
  {
    id: 'step-05',
    workflowId: 'workflow-02',
    name: 'Transform and validate output',
    actor: 'QA reviewer',
    systemsTouched: ['PDF pipeline', 'Execution log'],
    handoffTo: 'operator',
    latencyMinutes: 30,
    aiSuitability: 'high',
    approvalRequired: false,
    governanceRisk: 'medium',
  },
  {
    id: 'step-06',
    workflowId: 'workflow-03',
    name: 'Refresh scores and evidence',
    actor: 'researcher',
    systemsTouched: ['Scoring engine', 'Evidence room'],
    handoffTo: 'governance reviewer',
    latencyMinutes: 40,
    aiSuitability: 'high',
    approvalRequired: false,
    governanceRisk: 'medium',
  },
  {
    id: 'step-07',
    workflowId: 'workflow-03',
    name: 'Run policy checks on recommendations',
    actor: 'governance reviewer',
    systemsTouched: ['Policy engine', 'Approval service'],
    handoffTo: 'human owner',
    latencyMinutes: 25,
    aiSuitability: 'medium',
    approvalRequired: true,
    governanceRisk: 'high',
  },
];

export const agents: AgentProfile[] = [
  {
    id: 'agent-researcher',
    role: 'Researcher',
    model: 'gpt-5.4-mini',
    autonomy: 'A1',
    defaultMode: 'ai-run',
    allowedActions: ['Collect evidence', 'Summarize findings', 'Create internal issues'],
    blockedActions: ['External commitments', 'Policy edits'],
    status: 'active',
  },
  {
    id: 'agent-strategist',
    role: 'Strategist',
    model: 'gpt-5.4',
    autonomy: 'A1',
    defaultMode: 'hybrid',
    allowedActions: ['Draft recommendations', 'Compare ventures', 'Draft experiments'],
    blockedActions: ['Reprioritize ventures without approval', 'Spend money'],
    status: 'active',
  },
  {
    id: 'agent-coder',
    role: 'Coder',
    model: 'gpt-5.3-codex',
    autonomy: 'A1',
    defaultMode: 'hybrid',
    allowedActions: ['Draft code', 'Open branches', 'Write tests'],
    blockedActions: ['Merge protected branches', 'Create production secrets'],
    status: 'active',
  },
  {
    id: 'agent-qa',
    role: 'QA reviewer',
    model: 'gpt-5.4-mini',
    autonomy: 'A1',
    defaultMode: 'ai-run',
    allowedActions: ['Validate outputs', 'Flag regressions', 'Attach evidence'],
    blockedActions: ['Override defects silently'],
    status: 'active',
  },
  {
    id: 'agent-docs',
    role: 'Documentation agent',
    model: 'gpt-5.4-mini',
    autonomy: 'A1',
    defaultMode: 'ai-run',
    allowedActions: ['Update docs', 'Draft reviews'],
    blockedActions: ['Approve policy exceptions'],
    status: 'active',
  },
  {
    id: 'agent-workflow',
    role: 'Workflow analyst',
    model: 'gpt-5.4',
    autonomy: 'A1',
    defaultMode: 'hybrid',
    allowedActions: ['Decompose workflows', 'Estimate latency', 'Classify automation fit'],
    blockedActions: ['Finalize external promises'],
    status: 'active',
  },
  {
    id: 'agent-governance',
    role: 'Governance reviewer',
    model: 'gpt-5.4',
    autonomy: 'A0',
    defaultMode: 'human-led',
    allowedActions: ['Run policy checks', 'Log exceptions', 'Require approvals'],
    blockedActions: ['Self-authorize irreversible actions'],
    status: 'guarded',
  },
  {
    id: 'agent-operator',
    role: 'Operator',
    model: 'gpt-5.4-mini',
    autonomy: 'A1',
    defaultMode: 'hybrid',
    allowedActions: ['Manage queues', 'Escalate exceptions', 'Execute approved tasks'],
    blockedActions: ['Change priorities', 'Spend money'],
    status: 'active',
  },
];

export const humans: HumanProfile[] = [
  {
    id: 'human-adam',
    name: 'Adam Goodwin',
    role: 'Owner',
    authority: ['Budget approval', 'Priority changes', 'External commitments', 'Policy changes'],
  },
  {
    id: 'human-tech-lead',
    name: 'Hybrid Session',
    role: 'Technical lead',
    authority: ['Architecture sign-off', 'Protected branch approval', 'Operational overrides'],
  },
  {
    id: 'human-ops',
    name: 'Operations lead',
    role: 'Operator',
    authority: ['Queue exceptions', 'Manual QA acceptance'],
  },
];

export const tools: ToolProfile[] = [
  {
    id: 'tool-github',
    name: 'GitHub',
    purpose: 'Issue creation, branch workflows, review collection, CI visibility',
    approvalRequired: 'Protected branch merge and repository admin changes',
    prohibitedUse: 'Silent merges or repo settings changes without human approval',
  },
  {
    id: 'tool-supabase',
    name: 'Supabase',
    purpose: 'Data persistence, auth, and auditable control-plane storage',
    approvalRequired: 'Schema changes in production',
    prohibitedUse: 'Production data deletion without runbook and approval',
  },
  {
    id: 'tool-shell',
    name: 'Local shell',
    purpose: 'Code execution, tests, and internal automation',
    approvalRequired: 'Commands with spending or destructive side effects',
    prohibitedUse: 'Destructive resets or unauthorized secrets access',
  },
  {
    id: 'tool-web',
    name: 'Web research',
    purpose: 'Collect external evidence and benchmark supporting context',
    approvalRequired: 'Publishing or outbound commitments',
    prohibitedUse: 'Unsourced recommendations presented as fact',
  },
];

export const policies: Policy[] = [
  {
    id: 'policy-01',
    name: 'Protected branch integrity',
    scope: 'Source control',
    rule: 'Agents may draft code and open branches but may not merge protected branches.',
    humanApprovalRequired: true,
  },
  {
    id: 'policy-02',
    name: 'Capital preservation',
    scope: 'Money movement',
    rule: 'Any spending, subscription creation, or financial commitment requires human approval.',
    humanApprovalRequired: true,
  },
  {
    id: 'policy-03',
    name: 'Priority authority',
    scope: 'Portfolio allocation',
    rule: 'Agents may recommend reprioritization but cannot enact it without owner approval.',
    humanApprovalRequired: true,
  },
  {
    id: 'policy-04',
    name: 'Evidence before recommendation',
    scope: 'Decision quality',
    rule: 'Recommendations must reference metrics, logs, workflow analysis, or prior outcomes.',
    humanApprovalRequired: false,
  },
  {
    id: 'policy-05',
    name: 'Strategic focus guardrail',
    scope: 'Attention allocation',
    rule:
      'Agents should flag work that is off-roadmap, weakly evidenced, or novelty-driven, and route it into a parking lot or experiment instead of expanding the active plan.',
    humanApprovalRequired: false,
  },
];

export const approvals: Approval[] = [
  {
    id: 'approval-01',
    subject: 'AI Consulting Build offer redesign',
    owner: 'Adam Goodwin',
    status: 'approved',
    threshold: 'Owner sign-off',
  },
  {
    id: 'approval-02',
    subject: 'Freedom OS Engine scoring weight update',
    owner: 'Adam Goodwin',
    status: 'pending',
    threshold: 'Owner + governance reviewer',
  },
  {
    id: 'approval-03',
    subject: 'PDF Flow refund policy adjustment',
    owner: 'Operations lead',
    status: 'pending',
    threshold: 'Owner sign-off',
  },
];

export const evidenceItems: EvidenceItem[] = [
  {
    id: 'evidence-01',
    title: 'Readiness audit conversion notes',
    type: 'customer-signal',
    source: 'AI Consulting Build workshop log',
    summary: 'Prospects respond best when workflow bottlenecks are quantified with a next-step sprint offer.',
    relatedEntity: 'venture-ai-consulting',
  },
  {
    id: 'evidence-02',
    title: 'Proposal cycle time delta',
    type: 'metric',
    source: 'Internal tracking',
    summary: 'Workflow teardown package reduces proposal drafting time by roughly 38 percent.',
    relatedEntity: 'venture-ai-consulting',
  },
  {
    id: 'evidence-03',
    title: 'PDF throughput snapshot',
    type: 'metric',
    source: 'Clean PDF Build ops dashboard',
    summary: 'Queue spikes are concentrated in jobs requiring manual classification before transformation.',
    relatedEntity: 'venture-pdf-flow',
  },
  {
    id: 'evidence-04',
    title: 'Quality rework log',
    type: 'workflow-log',
    source: 'QA exception archive',
    summary: 'Most rework comes from ambiguous source documents and missing QA checkpoints.',
    relatedEntity: 'venture-pdf-flow',
  },
  {
    id: 'evidence-05',
    title: 'Founder time audit',
    type: 'financial',
    source: 'Weekly review worksheet',
    summary: 'Too much time is still spent switching between ventures without a clear allocation rule.',
    relatedEntity: 'venture-freedom-engine',
  },
  {
    id: 'evidence-06',
    title: 'Governance preflight baseline',
    type: 'governance',
    source: 'Repository preflight log',
    summary: 'The operating system repo now passes local governance preflight with zero warnings.',
    relatedEntity: 'venture-freedom-engine',
  },
  {
    id: 'evidence-07',
    title: 'Focus drift observation',
    type: 'governance',
    source: 'Founder operating note',
    summary:
      'Novel but weakly connected tasks can feel urgent and attractive even when they are not the best next move for freedom creation.',
    relatedEntity: 'venture-freedom-engine',
  },
];

export const executions: Execution[] = [
  {
    id: 'execution-01',
    workflowId: 'workflow-01',
    agentId: 'agent-workflow',
    status: 'completed',
    outcome: 'Workflow decomposition produced a sprint-ready consulting offer outline.',
    evidenceIds: ['evidence-01', 'evidence-02'],
    humanEscalation: true,
  },
  {
    id: 'execution-02',
    workflowId: 'workflow-02',
    agentId: 'agent-operator',
    status: 'awaiting-approval',
    outcome: 'Dashboard draft surfaced queue exceptions needing owner policy guidance.',
    evidenceIds: ['evidence-03', 'evidence-04'],
    humanEscalation: true,
  },
  {
    id: 'execution-03',
    workflowId: 'workflow-03',
    agentId: 'agent-governance',
    status: 'blocked',
    outcome: 'Priority update was held because the scoring weight change is still pending approval.',
    evidenceIds: ['evidence-05', 'evidence-06'],
    humanEscalation: true,
  },
];

export const overrides: Override[] = [
  {
    id: 'override-01',
    subject: 'Temporary manual prioritization of AI Consulting Build',
    reason: 'Immediate revenue learning outweighs platform sequencing this week.',
    owner: 'Adam Goodwin',
    followUp: 'Re-run scoring after next workshop sprint and either ratify or unwind the override.',
  },
];

export const integrations: Integration[] = [
  {
    id: 'integration-ai-consulting',
    name: 'AI Consulting Build',
    domain: 'Workflow readiness and implementation',
    status: 'live',
    note: 'Primary V1 operating domain and top candidate for first deep integration.',
  },
  {
    id: 'integration-pdf-flow',
    name: 'EasyDraftDocs / PDF Flow',
    domain: 'Document operations throughput',
    status: 'live',
    note: 'Provides measurable execution telemetry and owner dashboard use cases.',
  },
  {
    id: 'integration-github',
    name: 'GitHub workflow',
    domain: 'Code execution and review control plane',
    status: 'live',
    note: 'Used for issue creation, branches, reviews, and protected-branch controls.',
  },
];

export const connectSessions: ConnectSession[] = [
  {
    id: 'connect-session-01',
    freedomSessionId: 'freedom-session-desktop-01',
    title: 'Freedom',
    assistantName: 'Freedom',
    originSurface: 'desktop_shell',
    kind: 'operator',
    rootPath: '/home/adamgoodwin/code/agents/the-freedom-engine-os',
    workspaceLabel: 'Freedom Desktop Shell',
    auditCorrelationId: 'audit-connect-01',
    status: 'live',
    lastSummary: 'Desktop shell is online and sharing the primary governed operator session.',
    startedAt: '2026-04-13T08:15:00.000Z',
    lastActivityAt: '2026-04-13T08:28:00.000Z',
  },
  {
    id: 'connect-session-02',
    freedomSessionId: 'freedom-session-phone-01',
    title: 'Freedom',
    assistantName: 'Freedom',
    originSurface: 'mobile_companion',
    kind: 'operator',
    rootPath: '/home/adamgoodwin/code/agents/the-freedom-engine-os',
    workspaceLabel: 'Freedom Phone Companion',
    auditCorrelationId: 'audit-connect-02',
    status: 'live',
    lastSummary: 'Phone-originated operator chat is synced through Freedom Connect metadata.',
    startedAt: '2026-04-13T08:19:00.000Z',
    lastActivityAt: '2026-04-13T08:31:00.000Z',
  },
  {
    id: 'connect-session-03',
    freedomSessionId: 'freedom-session-build-01',
    title: 'Builder Routing',
    assistantName: 'Freedom',
    originSurface: 'mobile_companion',
    kind: 'build_request',
    rootPath: '/home/adamgoodwin/code/agents/the-freedom-engine-os',
    workspaceLabel: 'Governed Builder Flow',
    auditCorrelationId: 'audit-connect-03',
    status: 'needs-attention',
    lastSummary: 'Agent-build request is paused at policy review until the external builder route is confirmed.',
    startedAt: '2026-04-13T08:24:00.000Z',
    lastActivityAt: '2026-04-13T08:33:00.000Z',
  },
];

export const connectEvents: ConnectEvent[] = [
  {
    id: 'connect-event-01',
    sessionId: 'connect-session-02',
    source: 'mobile_companion',
    intent: 'operator_chat',
    summary: 'Phone companion paired back into the primary Freedom session without creating a second assistant identity.',
    governanceImpact: 'info',
    createdAt: '2026-04-13T08:20:00.000Z',
  },
  {
    id: 'connect-event-02',
    sessionId: 'connect-session-03',
    source: 'mobile_companion',
    intent: 'build_request',
    summary: 'Phone-originated request to evolve the desktop shell was routed into the governed builder path.',
    governanceImpact: 'builder-routed',
    createdAt: '2026-04-13T08:26:00.000Z',
  },
  {
    id: 'connect-event-03',
    sessionId: 'connect-session-03',
    source: 'desktop_shell',
    intent: 'approval',
    summary: 'Desktop shell surfaced the pending builder approval in the control plane instead of silently executing.',
    governanceImpact: 'approval-needed',
    createdAt: '2026-04-13T08:29:00.000Z',
  },
];

export const trustedContactPolicies: TrustedContactPolicy[] = [
  {
    id: 'trusted-contact-01',
    label: 'Owner-approved outbound',
    scope: 'Freedom Connect',
    trustedRecipients: ['Adam Goodwin'],
    approvalRequired: false,
  },
];

export const outboundDecisions: OutboundDecision[] = [
  {
    id: 'outbound-decision-01',
    channel: 'email',
    recipient: 'Adam Goodwin',
    summary: 'Completed session summary can be delivered externally only after an explicit in-session confirmation.',
    approvalState: 'pending',
  },
];

export const skillDefinitions: SkillDefinition[] = [
  {
    id: 'skill-builder-orchestrator',
    name: 'Builder Orchestrator',
    category: 'builder',
    purpose:
      'Decompose a requested capability into parallel tracks for spec, implementation, and governed artifact production.',
    status: 'learning',
    validationStatus: 'needs-evidence',
    parallelMode: 'parallel-native',
    maxConcurrentBranches: 3,
    preferredBranches: ['spec', 'implementation', 'governance'],
    lastLearnedAt: '2026-04-13T08:25:00.000Z',
  },
  {
    id: 'skill-repo-research',
    name: 'Repo Research',
    category: 'research',
    purpose:
      'Explore codebases and docs in bounded parallel threads before a build or self-evolution decision is approved.',
    status: 'internalized',
    validationStatus: 'validated',
    parallelMode: 'parallel-capable',
    maxConcurrentBranches: 4,
    preferredBranches: ['docs', 'runtime', 'ui', 'tests'],
    lastLearnedAt: '2026-04-12T14:10:00.000Z',
  },
  {
    id: 'skill-governance-check',
    name: 'Governance Check',
    category: 'validation',
    purpose:
      'Run policy, evidence, and release checks after branch work converges back into one governed decision.',
    status: 'internalized',
    validationStatus: 'validated',
    parallelMode: 'serial-only',
    maxConcurrentBranches: 1,
    preferredBranches: ['policy-review'],
    lastLearnedAt: '2026-04-12T15:40:00.000Z',
  },
];

export const selfEvolvingFunctions: SelfEvolvingFunction[] = [
  {
    id: 'self-evolving-function-01',
    name: 'Capability Internalization',
    objective:
      'Move repeated external build paths into validated internal skills only after they can reproduce governed outputs.',
    status: 'building',
    trigger: 'Repeated builder-routed requests for desktop and mobile Freedom surfaces.',
    parallelMode: 'parallel-native',
    activeBranches: ['spec capture', 'implementation replay', 'governance artifact diff'],
    branchCoordinatorSkillId: 'skill-builder-orchestrator',
    nextPromotionGate: 'Three clean governed reproductions with matching docs, tests, and audit traces.',
    auditCorrelationId: 'audit-connect-03',
  },
  {
    id: 'self-evolving-function-02',
    name: 'Parallel Validation Learning',
    objective:
      'Teach Freedom when to fan work out in parallel and when to collapse back into a single approval-bearing lane.',
    status: 'planning',
    trigger: 'Operator requests for concurrent research, design, and implementation while keeping one assistant identity.',
    parallelMode: 'parallel-capable',
    activeBranches: ['routing policy draft', 'skill registry update'],
    branchCoordinatorSkillId: 'skill-governance-check',
    nextPromotionGate: 'Validated policy proving safe branch fan-out without bypassing builder or approval gates.',
    auditCorrelationId: 'audit-connect-05',
  },
  {
    id: 'self-evolving-function-03',
    name: 'Conversation Learning Loop',
    objective:
      'Continuously extract durable operating preferences, focus patterns, and repeated capability needs from active conversations without bypassing approval gates.',
    status: 'planning',
    trigger: 'Repeated voice and operator-chat sessions surface recurring preferences, focus drift, or requests for better internal tooling.',
    parallelMode: 'parallel-capable',
    activeBranches: ['learning signal capture', 'focus guardrail prompts', 'approval-gated self-programming queue'],
    branchCoordinatorSkillId: 'skill-governance-check',
    nextPromotionGate: 'Validated proof that learned patterns improve guidance quality without causing silent behavior drift or unauthorized code changes.',
    auditCorrelationId: 'audit-connect-06',
  },
];

export const agentBuildRequests: AgentBuildRequest[] = [
  {
    id: 'build-request-01',
    capability: 'Freedom-first desktop shell',
    requestedFrom: 'desktop_shell',
    requestedBy: 'Freedom',
    status: 'routed-to-builder',
    builder: 'New Build Agent',
    executionMode: 'parallel-build',
    parallelLaneCount: 3,
    coordinatorSkillId: 'skill-builder-orchestrator',
    routeReason: 'Non-internalized build paths must use the external governed builder.',
    auditCorrelationId: 'audit-connect-03',
    requestedAt: '2026-04-13T08:27:00.000Z',
  },
  {
    id: 'build-request-02',
    capability: 'Freedom mobile companion rebrand',
    requestedFrom: 'mobile_companion',
    requestedBy: 'Freedom',
    status: 'pending-approval',
    builder: 'New Build Agent',
    executionMode: 'parallel-validation',
    parallelLaneCount: 2,
    coordinatorSkillId: 'skill-governance-check',
    routeReason: 'Mobile UI work is allowed, but release and pairing behavior still require approval.',
    auditCorrelationId: 'audit-connect-04',
    requestedAt: '2026-04-13T08:32:00.000Z',
  },
  {
    id: 'build-request-03',
    capability: 'Conversation learning + focus guardrail runtime',
    requestedFrom: 'desktop_shell',
    requestedBy: 'Freedom',
    status: 'pending-approval',
    builder: 'New Build Agent',
    executionMode: 'serial',
    parallelLaneCount: 1,
    coordinatorSkillId: 'skill-governance-check',
    routeReason: 'Freedom may propose self-programming improvements, but runtime behavior or code changes still require explicit approval before execution.',
    auditCorrelationId: 'audit-connect-06',
    requestedAt: '2026-04-15T17:15:00.000Z',
  },
];

// ─── Capability definitions (Learning Registry) ───────────────────────────────

export const capabilityDefinitions: CapabilityDefinition[] = [
  {
    id: 'cap-voice-layer',
    name: 'Voice Layer',
    description: 'LiveKit WebRTC + OpenAI Realtime voice interface with mic-mute self-interruption fix.',
    source: 'internal',
    state: 'internalized',
    internalizationStatus: 'internalized',
    runtimeCost: 'medium',
    modelPreference: 'gpt-4o-realtime-preview',
    safetyNotes: 'Mic must be muted while agent audio plays. Never expose LIVEKIT_API_SECRET to the browser.',
    builderDependency: null,
    validationRecord: {
      id: 'val-voice-layer-01',
      capabilityId: 'cap-voice-layer',
      governanceOutputsMatch: true,
      docArtifactsMatch: true,
      runtimeCostRecorded: true,
      validatedAt: '2026-04-14T20:00:00.000Z',
      validatedBy: 'Claude Code',
    },
    learningRecords: [
      {
        id: 'lr-voice-01',
        capabilityId: 'cap-voice-layer',
        event: 'Phase 1 build complete — lint, typecheck, build all pass',
        provenance: 'commit 69ede31',
        modelPreference: 'claude-sonnet-4-6',
        safetyNotes: 'Mic mute handler must not be removed.',
        internalizationStatus: 'internalized',
        externalBuilderStillRequired: false,
        recordedAt: '2026-04-14T20:00:00.000Z',
      },
    ],
    usageCount: 1,
    lastUsedAt: '2026-04-14T20:00:00.000Z',
    coreAdmission: false,
  },
  {
    id: 'cap-agent-scaffold',
    name: 'New Build Agent scaffold',
    description: 'Canonical workflow for creating governed agent artifacts: blueprint, governance bundle, validation checklist, and promotion record.',
    source: 'external-builder',
    state: 'validating',
    internalizationStatus: 'in-progress',
    runtimeCost: 'high',
    modelPreference: 'local-default',
    safetyNotes: 'All agent creation must route through this path until internalization is validated.',
    builderDependency: {
      id: 'dep-new-build-agent',
      capabilityId: 'cap-agent-scaffold',
      builderName: 'New Build Agent',
      required: true,
      replacedBy: null,
    },
    validationRecord: null,
    learningRecords: [
      {
        id: 'lr-scaffold-01',
        capabilityId: 'cap-agent-scaffold',
        event: 'Scaffold pattern observed across 3 agent-build requests; governance outputs consistent',
        provenance: 'seed-data audit-agent-01..03',
        modelPreference: 'local-default',
        safetyNotes: 'Do not internalize until governance output parity is confirmed end-to-end.',
        internalizationStatus: 'in-progress',
        externalBuilderStillRequired: true,
        recordedAt: '2026-04-13T09:00:00.000Z',
      },
    ],
    usageCount: 3,
    lastUsedAt: '2026-04-13T09:00:00.000Z',
    coreAdmission: false,
  },
  {
    id: 'cap-model-router',
    name: 'Model Router',
    description: 'Local-first model tier selection with permissioned escalation to Codex or Claude Code.',
    source: 'internal',
    state: 'building',
    internalizationStatus: 'not-started',
    runtimeCost: 'low',
    modelPreference: 'local-default',
    safetyNotes: 'No silent provider escalation. Every escalation must be audited.',
    builderDependency: null,
    validationRecord: null,
    learningRecords: [],
    usageCount: 0,
    lastUsedAt: '',
    coreAdmission: true,
  },
  {
    id: 'cap-conversation-learning',
    name: 'Conversation Learning + Focus Guardrail',
    description: 'Always-on capture of durable partner signals from conversation, plus approval-gated self-programming requests for runtime improvements.',
    source: 'internal',
    state: 'building',
    internalizationStatus: 'in-progress',
    runtimeCost: 'low',
    modelPreference: 'local-default',
    safetyNotes: 'Learning may shape future guidance, but runtime or code changes must remain approval-gated and auditable.',
    builderDependency: {
      id: 'dep-conversation-learning',
      capabilityId: 'cap-conversation-learning',
      builderName: 'New Build Agent',
      required: true,
      replacedBy: null,
    },
    validationRecord: null,
    learningRecords: [
      {
        id: 'lr-conversation-learning-01',
        capabilityId: 'cap-conversation-learning',
        event: 'Partner posture expanded toward always-on learning capture and approval-gated self-programming requests.',
        provenance: 'voice runtime + control-plane pass 2026-04-15',
        modelPreference: 'local-default',
        safetyNotes: 'Do not auto-apply learned changes; require explicit approval for self-programming.',
        internalizationStatus: 'in-progress',
        externalBuilderStillRequired: true,
        recordedAt: '2026-04-15T17:15:00.000Z',
      },
    ],
    usageCount: 1,
    lastUsedAt: '2026-04-15T17:15:00.000Z',
    coreAdmission: true,
  },
  {
    id: 'cap-freedom-connect',
    name: 'Freedom Connect',
    description: 'Cross-cutting communication router: wake, email, text, voice, operator chat. Dual-surface (desktop + mobile).',
    source: 'internal',
    state: 'internalized',
    internalizationStatus: 'internalized',
    runtimeCost: 'low',
    modelPreference: 'local-default',
    safetyNotes: 'Non-trusted outbound must trigger approval. No silent external sends.',
    builderDependency: null,
    validationRecord: {
      id: 'val-connect-01',
      capabilityId: 'cap-freedom-connect',
      governanceOutputsMatch: true,
      docArtifactsMatch: true,
      runtimeCostRecorded: true,
      validatedAt: '2026-04-12T14:00:00.000Z',
      validatedBy: 'Claude Code',
    },
    learningRecords: [],
    usageCount: 12,
    lastUsedAt: '2026-04-14T18:00:00.000Z',
    coreAdmission: true,
  },
];

// ─── Escalation requests + decisions (Model Router) ───────────────────────────

export const escalationRequests: EscalationRequest[] = [
  {
    id: 'esc-01',
    taskSummary: 'Generate full voice-layer spec including LiveKit + OpenAI Realtime architecture',
    whyLocalInsufficient: 'Spec required broad repo-wide synthesis, precise TypeScript patterns, and cross-checking against existing codebase conventions.',
    recommendation: {
      tier: 'escalate-with-approval',
      provider: 'openai',
      reason: 'OpenAI is the recommended first escalation lane for structured drafting, with operator choice still preserved.',
    },
    availableProviders: ['openai', 'claude-code', 'codex', 'local'],
    operatorSelection: 'claude-code',
    expectedBenefit: 'Complete, immediately buildable spec with correct type signatures and file inventory.',
    costSpeedTradeoff: 'Single session; cost justified by months of voice implementation time saved.',
    requestedAt: '2026-04-14T10:00:00.000Z',
    status: 'approved',
  },
  {
    id: 'esc-02',
    taskSummary: 'Implement voice layer Phase 1 from spec (10 files, LiveKit, framer-motion)',
    whyLocalInsufficient: 'Implementation required awareness of existing component patterns, TypeScript strict mode, and precise LiveKit API signatures.',
    recommendation: {
      tier: 'escalate-with-approval',
      provider: 'openai',
      reason: 'OpenAI is the first suggested escalation option, but Freedom should stop here so the operator can choose Codex if deeper coding power is the better fit.',
    },
    availableProviders: ['openai', 'codex', 'claude-code', 'local'],
    operatorSelection: 'codex',
    expectedBenefit: 'All 10 files correct on first pass; lint + typecheck + build all pass.',
    costSpeedTradeoff: 'Single session at higher quality than multiple local iterations.',
    requestedAt: '2026-04-14T14:00:00.000Z',
    status: 'approved',
  },
  {
    id: 'esc-03',
    taskSummary: 'Draft Freedom Core + Self-Evolving Platform architectural plan',
    whyLocalInsufficient: 'Plan required synthesising governance model, learning registry design, model routing policy, and capability layer boundaries into a single coherent document.',
    recommendation: {
      tier: 'escalate-with-approval',
      provider: 'openai',
      reason: 'OpenAI is the first suggested escalation lane, but the operator may still prefer Claude Code for broader synthesis.',
    },
    availableProviders: ['openai', 'claude-code', 'codex', 'local'],
    operatorSelection: 'claude-code',
    expectedBenefit: 'Actionable spec that guides Phase 2 implementation without ambiguity.',
    costSpeedTradeoff: 'One session; avoids weeks of design drift.',
    requestedAt: '2026-04-14T19:00:00.000Z',
    status: 'approved',
  },
];

export const escalationDecisions: EscalationDecision[] = [
  {
    id: 'escdec-01',
    escalationRequestId: 'esc-01',
    decision: 'approved',
    selectedProvider: 'claude-code',
    decidedBy: 'Adam',
    outcome: 'Spec delivered and committed as docs/specs/voice-layer-v1-spec.md.',
    decidedAt: '2026-04-14T10:05:00.000Z',
  },
  {
    id: 'escdec-02',
    escalationRequestId: 'esc-02',
    decision: 'approved',
    selectedProvider: 'codex',
    decidedBy: 'Adam',
    outcome: 'Phase 1 complete. Commit 69ede31. All validation gates pass.',
    decidedAt: '2026-04-14T14:10:00.000Z',
  },
  {
    id: 'escdec-03',
    escalationRequestId: 'esc-03',
    decision: 'approved',
    selectedProvider: 'claude-code',
    decidedBy: 'Adam',
    outcome: 'Plan committed as docs/specs/freedom-core-self-evolving-platform-plan.md.',
    decidedAt: '2026-04-14T19:05:00.000Z',
  },
];

export const executionBudgets: ExecutionBudget[] = getExecutionBudgetDefaults();

export const documentationDecisions: DocumentationDecision[] = [
  {
    id: 'docdec-01',
    sourceSessionId: 'connect-session-03',
    sourceKind: 'build_request',
    disposition: 'document',
    rationale: 'Builder-routed requests change governed implementation direction and should remain retrievable.',
    retrievalValue: 'high',
    decidedAt: '2026-04-13T08:30:00.000Z',
  },
  {
    id: 'docdec-02',
    sourceSessionId: 'connect-session-01',
    sourceKind: 'operator_chat',
    disposition: 'summarize',
    rationale: 'Conversation contained durable partner preferences but not enough unique detail to keep full chat transcript as canonical knowledge.',
    retrievalValue: 'medium',
    decidedAt: '2026-04-15T17:25:00.000Z',
  },
  {
    id: 'docdec-03',
    sourceSessionId: null,
    sourceKind: 'internal-review',
    disposition: 'discard',
    rationale: 'Scratch comparison notes were superseded by the finalized platform spec and would only add retrieval noise.',
    retrievalValue: 'low',
    decidedAt: '2026-04-16T20:00:00.000Z',
  },
];

export const knowledgeArtifacts: KnowledgeArtifact[] = [
  {
    id: 'artifact-01',
    title: 'Freedom Core + Self-Evolving Platform Plan',
    kind: 'spec',
    summary: 'Canonical Phase 2 direction for core architecture, outcome engine, knowledge governance, and workforce orchestration.',
    sourceDecisionId: 'docdec-01',
    placementDecisionId: 'place-01',
    permanence: 'canonical',
    canonical: true,
    owner: 'hybrid-session',
    lastReviewedAt: '2026-04-16T20:15:00.000Z',
  },
  {
    id: 'artifact-02',
    title: 'Conversation Learning Summary',
    kind: 'summary',
    summary: 'Condensed record of durable partner preferences, focus drift patterns, and self-programming triggers from recent operator chats.',
    sourceDecisionId: 'docdec-02',
    placementDecisionId: 'place-02',
    permanence: 'durable',
    canonical: false,
    owner: 'Freedom',
    lastReviewedAt: '2026-04-15T17:30:00.000Z',
  },
];

export const artifactPlacementDecisions: ArtifactPlacementDecision[] = [
  {
    id: 'place-01',
    artifactId: 'artifact-01',
    target: 'docs-specs',
    pathRecommendation: 'docs/specs/freedom-core-self-evolving-platform-plan.md',
    permanence: 'canonical',
    rationale: 'Long-lived implementation direction belongs in governed specs rather than ad hoc notes.',
    decidedAt: '2026-04-14T19:10:00.000Z',
  },
  {
    id: 'place-02',
    artifactId: 'artifact-02',
    target: 'runtime-store',
    pathRecommendation: 'Supabase durable memory + linked control-plane retrieval surface',
    permanence: 'durable',
    rationale: 'Reusable partner learning should stay queryable without cluttering canonical docs.',
    decidedAt: '2026-04-15T17:30:00.000Z',
  },
];

export const retrievalRecords: RetrievalRecord[] = [
  {
    id: 'retrieval-01',
    artifactId: 'artifact-01',
    summary: 'Canonical architectural plan for Freedom Phase 2.',
    tags: ['architecture', 'phase-2', 'governance', 'workforce', 'knowledge'],
    sourceLinks: ['docs/specs/freedom-core-self-evolving-platform-plan.md'],
    updatedAt: '2026-04-16T20:15:00.000Z',
    supersededBy: null,
  },
  {
    id: 'retrieval-02',
    artifactId: 'artifact-02',
    summary: 'Durable conversation patterns worth reusing in future operator guidance.',
    tags: ['memory', 'preferences', 'focus', 'self-programming'],
    sourceLinks: ['/api/freedom-memory'],
    updatedAt: '2026-04-15T17:30:00.000Z',
    supersededBy: null,
  },
];

export const canonicalSourceLinks: CanonicalSourceLink[] = [
  {
    id: 'canonical-01',
    concept: 'Freedom Phase 2 platform direction',
    canonicalArtifactId: 'artifact-01',
    supersedesArtifactIds: [],
    note: 'Use the spec as the first retrieval target before referring to scratch planning notes.',
  },
];

export const skillAcquisitionDecisions: SkillAcquisitionDecision[] = [
  {
    id: 'skilldec-01',
    skillName: 'Knowledge Stewardship',
    triggerPattern: 'Repeated need to decide which chats become durable docs versus summarized memory.',
    decision: 'learn-new-skill',
    expectedFreedomGain: 'high',
    validationMethod: 'Show consistent document/summarize/discard recommendations across conversation evals.',
    placement: 'capability-layer',
    decidedAt: '2026-04-16T20:20:00.000Z',
  },
  {
    id: 'skilldec-02',
    skillName: 'Builder Orchestrator',
    triggerPattern: 'Repeated governed agent-build requests through the New Build Agent path.',
    decision: 'strengthen-existing-skill',
    expectedFreedomGain: 'high',
    validationMethod: 'Governed artifact parity across repeated agent-build runs.',
    placement: 'capability-layer',
    decidedAt: '2026-04-13T09:05:00.000Z',
  },
];

export const knowledgeRetentionPolicies: KnowledgeRetentionPolicy[] = [
  {
    id: 'retain-01',
    label: 'Freedom knowledge hygiene baseline',
    keepWhen: [
      'A chat changes a decision, policy, workflow, or capability plan.',
      'The artifact becomes a likely future retrieval target.',
    ],
    summarizeWhen: [
      'The conversation has durable value but too much noise to keep as canonical text.',
      'The main value is the extracted pattern rather than the full transcript.',
    ],
    archiveWhen: [
      'The artifact was once useful but has been superseded by a clearer canonical source.',
    ],
    discardWhen: [
      'The chat is transient, duplicated, or unlikely to inform future decisions.',
      'Keeping it would create retrieval debt without adding durable value.',
    ],
    canonicalityRule: 'Each concept should have one clear source of truth before additional notes are retained.',
  },
];
