import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#dfe7f3" },
  mobileShell: { flex: 1, paddingHorizontal: 12, paddingTop: 10, gap: 10 },
  mobileTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    backgroundColor: "rgba(246, 250, 255, 0.82)",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(20, 52, 92, 0.08)"
  },
  mobileIdentity: { flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 12 },
  mobileIdentityMark: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "#12325b",
    alignItems: "center",
    justifyContent: "center"
  },
  mobileIdentityMarkLabel: { color: "#f8fbff", fontWeight: "800", fontSize: 22 },
  mobileIdentityCopy: { flex: 1, minWidth: 0, gap: 2 },
  mobileIdentityTitle: { color: "#10233e", fontSize: 20, lineHeight: 22, fontWeight: "800" },
  mobileIdentitySubtitle: { color: "#60728b", fontSize: 12, lineHeight: 16 },
  mobileQuickActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  mobileQuickAction: {
    minWidth: 52,
    height: 44,
    borderRadius: 12,
    paddingHorizontal: 12,
    backgroundColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(18, 50, 91, 0.08)"
  },
  mobileQuickActionLabel: { color: "#10233e", fontSize: 20, fontWeight: "800" },
  mobileQuickActionText: { color: "#10233e", fontSize: 13, fontWeight: "800" },
  mobileStatusStrip: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  mobileViewport: { flex: 1, minHeight: 0 },
  mobileDock: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: "rgba(15, 32, 56, 0.94)",
    borderRadius: 22,
    paddingHorizontal: 10,
    paddingTop: 10
  },
  mobileDockButton: {
    flex: 1,
    minHeight: 52,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center"
  },
  mobileDockButtonActive: { backgroundColor: "#4da7d3" },
  mobileDockLabel: { color: "#c6d8ea", fontWeight: "800", fontSize: 15 },
  mobileDockLabelActive: { color: "#0c213a" },
  heroCard: {
    backgroundColor: "#0b1526",
    borderRadius: 12,
    padding: 24,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(94, 162, 220, 0.2)",
    shadowColor: "#0b1526",
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8
  },
  assistantStageCard: {
    backgroundColor: "#102746",
    borderRadius: 12,
    padding: 18,
    gap: 10,
    borderWidth: 1,
    borderColor: "rgba(109, 177, 230, 0.18)"
  },
  stageHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  stageEyebrow: {
    color: "#a9d8ff",
    textTransform: "uppercase",
    letterSpacing: 1.1,
    fontWeight: "800",
    fontSize: 12
  },
  stageBadge: {
    color: "#d9efff",
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    overflow: "hidden",
    fontWeight: "700",
    fontSize: 12
  },
  stageTitle: { color: "#f4f9ff", fontSize: 24, lineHeight: 28, fontWeight: "800" },
  stageBody: { color: "#c8dbef", lineHeight: 21, fontSize: 14 },
  stageActionRow: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 4 },
  owlBadgeShell: {
    alignSelf: "center",
    width: 112,
    height: 132,
    alignItems: "center",
    justifyContent: "flex-start",
    marginBottom: 6
  },
  owlBadgeShellCompact: {
    width: 88,
    height: 104,
    marginBottom: 0
  },
  owlEarRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: -8,
    zIndex: 2
  },
  owlEar: {
    width: 18,
    height: 18,
    borderRadius: 4,
    backgroundColor: "#dcecff",
    borderWidth: 1,
    borderColor: "rgba(76, 145, 206, 0.36)",
    transform: [{ rotate: "45deg" }]
  },
  owlHead: {
    width: 88,
    height: 66,
    borderRadius: 22,
    backgroundColor: "#dfeefe",
    borderWidth: 1,
    borderColor: "rgba(76, 145, 206, 0.34)",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1
  },
  owlEyeCluster: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: "#173458",
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center"
  },
  owlEye: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#8fd9ff",
    alignItems: "center",
    justifyContent: "center"
  },
  owlPupil: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ffffff"
  },
  owlBeak: {
    marginTop: 8,
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 10,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    borderTopColor: "#6f90b8"
  },
  owlBody: {
    width: 58,
    height: 44,
    borderRadius: 18,
    marginTop: 8,
    backgroundColor: "#e8f2ff",
    borderWidth: 1,
    borderColor: "rgba(76, 145, 206, 0.3)",
    alignItems: "center",
    justifyContent: "center"
  },
  owlChest: {
    width: 26,
    height: 22,
    borderRadius: 10,
    backgroundColor: "#cddff4"
  },
  owlWingRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: -26,
    paddingHorizontal: 8
  },
  owlWing: {
    width: 20,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#dcecff",
    borderWidth: 1,
    borderColor: "rgba(76, 145, 206, 0.26)"
  },
  shellHeaderCard: {
    backgroundColor: "rgba(246, 250, 255, 0.96)",
    borderRadius: 12,
    padding: 14,
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(20, 52, 92, 0.08)",
    shadowColor: "#0b1526",
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
    marginBottom: 10
  },
  shellHeaderTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  shellHeaderTopStacked: { flexDirection: "column", alignItems: "stretch" },
  shellBrandCluster: { flex: 1, minWidth: 0, flexDirection: "row", gap: 12, alignItems: "flex-start" },
  shellBrandClusterStacked: { width: "100%" },
  shellBrandMark: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#12325b",
    alignItems: "center",
    justifyContent: "center"
  },
  shellBrandMarkLabel: { color: "#eff6ff", fontSize: 18, fontWeight: "800" },
  shellBrandCopy: { flex: 1, minWidth: 0, gap: 2 },
  shellBrandTitle: { fontSize: 24, lineHeight: 26, fontWeight: "800", color: "#10233e" },
  shellBrandTitleCompact: { fontSize: 22, lineHeight: 24 },
  shellBrandSubtitle: { color: "#5a6d87", fontSize: 13, lineHeight: 18 },
  shellHeaderActions: { flexDirection: "row", alignItems: "center", gap: 8, flexWrap: "wrap", justifyContent: "flex-end" },
  shellHeaderActionsStacked: { width: "100%", justifyContent: "flex-start" },
  header: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12, marginBottom: 10 },
  headerCopy: { flex: 1, minWidth: 0, paddingRight: 12 },
  headerActions: { alignItems: "flex-end", gap: 8 },
  headerActionButton: { minWidth: 148 },
  headerMetaRow: { marginTop: 10, gap: 8 },
  headerMenuButton: { alignSelf: "flex-start", minHeight: 42, paddingVertical: 10, paddingHorizontal: 14 },
  headerStatusText: { color: "#475569", lineHeight: 20 },
  voiceStatusText: { fontSize: 12, fontWeight: "700" },
  voiceStatusReady: { color: "#0f766e" },
  voiceStatusWarning: { color: "#92400e" },
  chatAppHeader: {
    alignItems: "center",
    marginBottom: 8,
    paddingHorizontal: 2
  },
  chatAppHeaderCopy: { flex: 1, minWidth: 0, gap: 2 },
  chatAppHeaderTitle: { fontSize: 23, lineHeight: 26, fontWeight: "800", color: "#0f172a" },
  chatAppHeaderSubtitle: { color: "#64748b", fontSize: 12, lineHeight: 16 },
  chatAppHeaderActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  iconButton: {
    minWidth: 42,
    height: 42,
    paddingHorizontal: 10,
    borderRadius: 8,
    backgroundColor: "rgba(255,255,255,0.92)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(18, 50, 91, 0.08)"
  },
  iconButtonWide: { minWidth: 88, flexGrow: 1 },
  iconButtonLabel: { color: "#10233e", fontWeight: "800", fontSize: 13 },
  warningIconButton: { backgroundColor: "#fff2d8" },
  topPanel: {
    backgroundColor: "rgba(244,248,255,0.92)",
    borderRadius: 10,
    padding: 12,
    gap: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "rgba(18, 50, 91, 0.08)"
  },
  panelLead: { color: "#50647f", lineHeight: 18, fontSize: 12, fontWeight: "700" },
  eyebrow: { color: "#99f6e4", textTransform: "uppercase", letterSpacing: 1.2, fontWeight: "800", fontSize: 12 },
  heroTitle: { fontSize: 31, lineHeight: 34, fontWeight: "800", color: "#f8fafc" },
  brand: { fontSize: 31, lineHeight: 34, fontWeight: "800", color: "#10233e" },
  heroBody: { color: "#cedcf0", lineHeight: 22, fontSize: 15 },
  subtitle: { color: "#5a6d87", marginTop: 2, fontSize: 15 },
  nav: { flexDirection: "row", gap: 8 },
  navCompact: { flexWrap: "wrap" },
  topActions: { flexDirection: "row", gap: 8 },
  topActionsStacked: { flexDirection: "column" },
  navButton: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: "#dde7f5",
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(18, 50, 91, 0.04)"
  },
  navButtonCompact: { minWidth: "31%" },
  navButtonActive: { backgroundColor: "#14345d" },
  navLabel: { color: "#3d526d", fontWeight: "700" },
  navLabelActive: { color: "#ffffff" },
  content: { gap: 14, paddingBottom: 28, flexGrow: 1 },
  screenContent: { flex: 1, gap: 14, paddingBottom: 12, minHeight: 0 },
  chatScreen: { flex: 1, minHeight: 0, gap: 8 },
  chatScrollArea: { flex: 1, minHeight: 0 },
  chatScrollContent: { gap: 10, paddingBottom: 8, flexGrow: 1 },
  card: {
    backgroundColor: "rgba(250,252,255,0.94)",
    borderRadius: 10,
    padding: 18,
    gap: 10,
    borderWidth: 1,
    borderColor: "rgba(18, 50, 91, 0.08)"
  },
  sessionCard: { backgroundColor: "rgba(255,255,255,0.98)" },
  sectionTitle: { fontSize: 20, fontWeight: "800", color: "#10233e" },
  supportingText: { color: "#5a6d87", lineHeight: 21 },
  metric: { color: "#334b66", lineHeight: 21 },
  rootPath: { color: "#10233e", fontFamily: "monospace", backgroundColor: "#f4f8fd", borderRadius: 8, padding: 12, borderWidth: 1, borderColor: "rgba(18, 50, 91, 0.06)" },
  rowBetween: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  preferenceCopy: { flex: 1, paddingRight: 14, gap: 2 },
  statusRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  statusChip: { borderRadius: 8, paddingHorizontal: 12, paddingVertical: 9 },
  statusChipTeal: { backgroundColor: "#d9eef8" },
  statusChipOrange: { backgroundColor: "#fff1df" },
  statusChipLabel: { fontWeight: "800", fontSize: 12 },
  statusChipLabelTeal: { color: "#166b88" },
  statusChipLabelOrange: { color: "#b8641f" },
  primaryButton: {
    backgroundColor: "#14345d",
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
    minHeight: 50,
    justifyContent: "center"
  },
  primaryLabel: { color: "#ffffff", fontWeight: "800" },
  secondaryButton: {
    backgroundColor: "#e2ebf8",
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: "center",
    minHeight: 50,
    justifyContent: "center"
  },
  topActionButton: { width: "100%" },
  topActionButtonStacked: { width: "100%" },
  secondaryLabel: { color: "#1b4f82", fontWeight: "800" },
  warningButton: { backgroundColor: "#fff2d8" },
  warningButtonLabel: { color: "#9a5b1a" },
  dangerButton: { backgroundColor: "#fee2e2" },
  dangerButtonLabel: { color: "#b91c1c" },
  disabledButton: { opacity: 0.45 },
  disconnectButton: {
    alignSelf: "flex-start",
    backgroundColor: "#fff1df",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10
  },
  disconnectLabel: { color: "#b8641f", fontWeight: "800" },
  error: { color: "#b91c1c", fontWeight: "600" },
  inputGroup: { gap: 6 },
  inputLabel: { color: "#334155", fontWeight: "700" },
  input: {
    borderWidth: 1,
    borderColor: "rgba(18, 50, 91, 0.1)",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 13,
    color: "#10233e",
    backgroundColor: "#f8fbff"
  },
  inputMultiline: {
    minHeight: 96,
    paddingTop: 14
  },
  chatSummaryCard: { paddingVertical: 14, gap: 8, flexShrink: 1 },
  chatSummaryHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  chatSummaryCopy: { flex: 1, gap: 8, minWidth: 0 },
  chatSummaryMeta: { alignItems: "flex-end", gap: 8 },
  chatSummaryBadgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, alignItems: "center" },
  chatSummaryTitle: { fontSize: 18, lineHeight: 22, fontWeight: "800", color: "#0f172a" },
  chatSummaryMetaLine: { color: "#64748b", lineHeight: 18, fontSize: 12 },
  chatChromeCard: { paddingVertical: 12, gap: 8 },
  chatResumeButton: { alignSelf: "flex-start", minHeight: 40, paddingVertical: 10, paddingHorizontal: 14 },
  messages: { gap: 8 },
  voiceSessionCard: { gap: 10, paddingVertical: 14 },
  voiceSessionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  voiceSessionCopy: { flex: 1, gap: 4 },
  voiceMeterTrack: {
    height: 10,
    borderRadius: 6,
    backgroundColor: "#d8e7f8",
    overflow: "hidden"
  },
  voiceMeterFill: {
    height: "100%",
    borderRadius: 6,
    backgroundColor: "#1d7aa6"
  },
  voicePreviewLabel: { color: "#1b4f82", fontWeight: "800", fontSize: 12, textTransform: "uppercase", letterSpacing: 0.7 },
  voiceMetrics: { color: "#5a6d87", fontSize: 12, lineHeight: 18 },
  chatComposerCard: { marginTop: 2, padding: 10, gap: 8 },
  voiceFirstFooterCard: { marginTop: 2, paddingVertical: 12, gap: 8 },
  insetCard: {
    backgroundColor: "#f6faff",
    borderRadius: 8,
    padding: 14,
    gap: 10,
    borderWidth: 1,
    borderColor: "rgba(18, 50, 91, 0.06)"
  },
  optionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  optionChip: {
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#e3ebf6"
  },
  optionChipActive: { backgroundColor: "#14345d" },
  optionChipLabel: { color: "#334b66", fontWeight: "700", fontSize: 12 },
  optionChipLabelActive: { color: "#ffffff" },
  optionChipMeta: { color: "#60758f", fontSize: 11, marginTop: 4, fontWeight: "600" },
  optionChipMetaActive: { color: "rgba(255,255,255,0.82)" },
  helperText: { color: "#687c97", fontSize: 12, lineHeight: 18 },
  messageBubble: {
    borderRadius: 10,
    padding: 12,
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(18, 50, 91, 0.06)"
  },
  userBubble: { backgroundColor: "#dcebf8" },
  assistantBubble: { backgroundColor: "rgba(255,255,255,0.96)" },
  messageHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 },
  messageRole: { fontWeight: "700", color: "#10233e" },
  messageTime: { color: "#6b7d95", fontSize: 12 },
  messageBlock: { gap: 8 },
  messageText: { color: "#334b66", lineHeight: 21 },
  messageCodeBlock: {
    backgroundColor: "#10233e",
    borderRadius: 8,
    padding: 12
  },
  messageCodeText: { color: "#e2e8f0", fontFamily: "monospace", lineHeight: 20 },
  messageMeta: { color: "#6b7d95", fontSize: 12 },
  messageActionButton: {
    alignSelf: "flex-start",
    marginTop: 2,
    backgroundColor: "#e2ebf8",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8
  },
  messageActionLabel: { color: "#1b4f82", fontWeight: "800", fontSize: 12 },
  workingBubble: { backgroundColor: "#fff7ed", borderColor: "rgba(184,100,31,0.12)" },
  workingBubbleRow: { flexDirection: "row", alignItems: "center", gap: 12 },
  workingGlyphWrap: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: "#fff2d8",
    alignItems: "center",
    justifyContent: "center"
  },
  workingGlyph: { fontSize: 20, color: "#b8641f", fontWeight: "800" },
  workingCopy: { flex: 1, gap: 2 },
  composer: {
    minHeight: 72,
    textAlignVertical: "top",
    borderWidth: 1,
    borderColor: "rgba(18, 50, 91, 0.1)",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: "#10233e",
    backgroundColor: "#f8fbff"
  },
  composerCompact: { minHeight: 60, maxHeight: 104 },
  actions: { flexDirection: "row", gap: 10, flexWrap: "wrap" },
  chatActions: { flexDirection: "column" },
  chatActionButton: { width: "100%" },
  chatComposerActions: { flexDirection: "row" },
  chatComposerActionButton: { flex: 1 },
  banner: {
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
    borderWidth: 1
  },
  errorBanner: {
    backgroundColor: "#fef2f2",
    borderColor: "#fecaca"
  },
  infoBanner: {
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe"
  },
  bannerLabel: {
    fontWeight: "700"
  },
  errorBannerLabel: {
    color: "#b91c1c"
  },
  infoBannerLabel: {
    color: "#1d4ed8"
  },
  operatorBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#d9eef8",
    color: "#166b88",
    fontWeight: "800",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12
  },
  kindBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#e3ebf6",
    color: "#1b4f82",
    fontWeight: "800",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12
  },
  pinnedBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#fff1df",
    color: "#b8641f",
    fontWeight: "800",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12
  },
  styleBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#e2ebf8",
    color: "#1b4f82",
    fontWeight: "800",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12
  }
});
